sudo: required
services:
  - docker

before_install:
  - docker build -t jeremyzhang1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jeremyzhang1/react-test npm test

after_success:
  - docker build -t jeremyzhang1/multi-client ./client
  - docker build -t jeremyzhang1/multi-nginx ./nginx
  - docker build -t jeremyzhang1/multi-server ./server
  - docker build -t jeremyzhang1/multi-worker ./worker
  # login docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker hub
  - docker push jeremyzhang1/multi-client
  - docker push jeremyzhang1/multi-nginx
  - docker push jeremyzhang1/multi-server
  - docker push jeremyzhang1/multi-worker